/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projek_akhir;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sigma
 */
public class Anggota_User extends javax.swing.JFrame {

    /**
     * Creates new form Anggota_User
     */
    public Anggota_User() {
        Koneksi conn = new Koneksi();
        initComponents();
        table();
        cari();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //void ambilID() {
//        Koneksi conn = new Koneksi();
//
//        try {
//            String sql = "SELECT id FROM register ORDER BY username ";
//            PreparedStatement pst = conn.getConnection().prepareStatement(sql);
//            
//
//            ResultSet rs = pst.executeQuery();
//
//            // Jika ada hasil dari query, set ID ke dalam JTextField 'id'
//            if (rs.next()) {
//                String userId = rs.getString("id");
//                username.setText(userId);
//            }
//
//            pst.close();
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
//        }
//    }


void cari() {
    Koneksi conn = new Koneksi();
    DefaultTableModel tableModel = new DefaultTableModel();
    tableModel.addColumn("ID");
    tableModel.addColumn("NIK");
    tableModel.addColumn("Username");
    tableModel.addColumn("Nama");
    tableModel.addColumn("No. Telp");
    tableModel.addColumn("Jenis Kelamin");
    tableModel.addColumn("Tanggal");
    tableModel.addColumn("Alamat");

    try {
        String nikToSearch = "%" + pencarian.getText() + "%";

        // Use PreparedStatement to avoid SQL injection
        String query = "SELECT * FROM anggota WHERE nik LIKE ?";
        PreparedStatement preparedStatement = conn.getConnection().prepareStatement(query);
        preparedStatement.setString(1, nikToSearch);

        ResultSet rs = preparedStatement.executeQuery();

        while (rs.next()) {
            java.util.Date tanggalDate = rs.getDate("tanggal");

            // Menambahkan data ke dalam tabelModel
            Object[] rowData = new Object[] {
                rs.getString("id"),
                rs.getString("nik"),
                rs.getString("username_user"),
                rs.getString("nama"),
                rs.getString("telp"),
                rs.getString("jenis_kelamin"),
                rs.getString("tanggal"),
                rs.getString("alamat"),
            };

            tableModel.addRow(rowData);
        }

        Tabel.setModel(tableModel);
        preparedStatement.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    }
}

    

    private void table() {
    Koneksi conn = new Koneksi();
    DefaultTableModel tableModel = new DefaultTableModel();
    tableModel.addColumn("ID"); 
    tableModel.addColumn("NIK");
    tableModel.addColumn("Username");
    tableModel.addColumn("Nama");
    tableModel.addColumn("No. Telp");
    tableModel.addColumn("Jenis Kelamin");
    tableModel.addColumn("Tanggal");
    tableModel.addColumn("Alamat");

    try {
        Statement st = conn.getConnection().createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM anggota");

        while (rs.next()) {
            java.util.Date tanggalDate = rs.getDate("tanggal");
//            String idRegister = rs.getString("id"); // Ambil nilai ID dari register

            // Menambahkan data ke dalam tabelModel
            Object[] rowData = new Object[] {
//                idRegister, // Menambahkan ID ke dalam rowData
//                rs.getString("id"),
                rs.getString("id"),
                rs.getString("nik"),
                rs.getString("username_user"),
                rs.getString("nama"),
                rs.getString("telp"),
                rs.getString("jenis_kelamin"),
                rs.getString("tanggal"),
                rs.getString("alamat"),
            };

            tableModel.addRow(rowData);
        }

        Tabel.setModel(tableModel);
        st.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    }
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nik = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        telp = new javax.swing.JTextField();
        laki = new javax.swing.JRadioButton();
        perem = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        pencarian = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Tanggal = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NIK");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAMA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 37, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NO. TELP");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 24));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("JENIS KELAMIN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TANGGAL GABUNG");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, 30));

        nik.setBackground(new java.awt.Color(204, 0, 204));
        nik.setForeground(new java.awt.Color(255, 255, 255));
        nik.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 200, -1));

        nama.setBackground(new java.awt.Color(204, 0, 204));
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 200, -1));

        telp.setBackground(new java.awt.Color(204, 0, 204));
        telp.setForeground(new java.awt.Color(255, 255, 255));
        telp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 200, -1));

        grup.add(laki);
        laki.setForeground(new java.awt.Color(255, 255, 255));
        laki.setText("Pria");
        jPanel1.add(laki, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 80, 30));

        grup.add(perem);
        perem.setForeground(new java.awt.Color(255, 255, 255));
        perem.setText("Wanita");
        jPanel1.add(perem, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 70, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 204));
        jButton1.setText("Daftar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 204));
        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 70, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ALAMAT");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 62, 20));

        alamat.setBackground(new java.awt.Color(204, 0, 204));
        alamat.setForeground(new java.awt.Color(255, 255, 255));
        alamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 200, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 204));
        jButton3.setText("Cari");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 343, -1, 30));
        jPanel1.add(pencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 342, 250, 30));

        jButton4.setBackground(new java.awt.Color(204, 0, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("EXIT");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 70, 40));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projek_Akhir2\\src\\Gambar\\LOGO.png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 120, 160));

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 810, 250));

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projek_Akhir2\\src\\Gambar\\—Pngtree—blue purple gradient circle_5487754 (1).png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 280, 700, 650));

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projek_Akhir2\\src\\Gambar\\—Pngtree—blue purple gradient circle_5487754 (1).png")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, -280, 700, 650));
        jPanel1.add(Tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 160, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("USERNAME");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 62, 20));

        username.setBackground(new java.awt.Color(204, 0, 204));
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 200, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                                
    String jk = null;

    if (laki.isSelected()) {
        jk = "Pria";
    } else if (perem.isSelected()) {
        jk = "Wanita";
    }

    String tmpl = "yyyy-MM-dd";
    SimpleDateFormat fn = new SimpleDateFormat(tmpl);
    String tanggal = fn.format(Tanggal.getDate());

    try {
        Koneksi conn = new Koneksi();

        String usernameRegister = username.getText();

        // Mengambil ID dari tabel register berdasarkan username
        String sqlID = "SELECT id FROM register WHERE username = ?";
        PreparedStatement pstID = conn.getConnection().prepareStatement(sqlID);
        pstID.setString(1, usernameRegister);
        ResultSet rsID = pstID.executeQuery();

        if (rsID.next()) {
            String idRegister = rsID.getString("id");

            // Melakukan penambahan data ke tabel anggota dengan memasukkan id dari register
            String sqlAnggota = "INSERT INTO anggota (nik, id, username_user, nama, telp, jenis_kelamin, tanggal, alamat) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pstAnggota = conn.getConnection().prepareStatement(sqlAnggota);

            pstAnggota.setString(1, nik.getText());
            pstAnggota.setString(2, idRegister); // Menggunakan ID dari register
            pstAnggota.setString(3, username.getText()); 
            pstAnggota.setString(4, nama.getText());
            pstAnggota.setString(5, telp.getText());
            pstAnggota.setString(6, jk);
            pstAnggota.setString(7, tanggal);
            pstAnggota.setString(8, alamat.getText());

            pstAnggota.executeUpdate();
            pstAnggota.close();

            table();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        } else {
            JOptionPane.showMessageDialog(null, "Username tidak ditemukan, data tidak disimpan");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan");
    }

// ...
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        nik.setText("");
        nama.setText("");
        telp.setText("");
        grup.clearSelection();
        alamat.setText("");
        Tanggal.setDate(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       cari();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       JOptionPane.showMessageDialog(null, "Apakah Yakin Untuk Keluar");
        this.setVisible(false);
       User New = new User();
       New.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anggota_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anggota_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anggota_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anggota_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anggota_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel;
    private com.toedter.calendar.JDateChooser Tanggal;
    private javax.swing.JTextField alamat;
    private javax.swing.ButtonGroup grup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField pencarian;
    private javax.swing.JRadioButton perem;
    private javax.swing.JTextField telp;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
