/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projek_akhir;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sigma
 */
public class Pinjam_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Pinjam_Admin
     */
    public Pinjam_Admin() {
        initComponents();
        table();
        cari();
        hapus();
    }
    
    void cari() {
    Koneksi conn = new Koneksi();
    DefaultTableModel tableModel = new DefaultTableModel();
    tableModel.addColumn("NIK");
    tableModel.addColumn("Nama");
    tableModel.addColumn("Tanggal");
    tableModel.addColumn("Barang");
    tableModel.addColumn("Pinjaman");
    tableModel.addColumn("Persetujuan");
    tableModel.addColumn("Waktu");
    try {
        String nimToSearch = "%" + pencarian.getText() + "%"; 

        String sql = "SELECT * FROM pinjam WHERE nik LIKE ?";
        PreparedStatement pst = conn.getConnection().prepareStatement(sql);
        pst.setString(1, nimToSearch);

        ResultSet rs = pst.executeQuery();
        while (rs.next()) {

            Object[] rowData = new Object[] {
                 rs.getString("nik"),
                rs.getString("nama"),
                rs.getString("tanggal"),
                rs.getString("barang"),
                rs.getString("pinjaman"),
                rs.getString("persetujuan"),
                rs.getString("waktu"),
                

            };

            tableModel.addRow(rowData);
        }

        Tabel.setModel(tableModel);
        pst.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    }
}
    private void hapus(){
        nik.setText("");
        nama.setText("");
        Tanggal.setDate(null);
        Menu.setSelectedIndex(0);
        Obama.setSelectedIndex(0);
        waktu.setSelectedIndex(0);
    }
    
//     void Persetujuan(boolean atur) {
//    persetujuan.setEnabled(atur);
//}
//    
   private void table() {
    Koneksi conn = new Koneksi();
    DefaultTableModel tableModel = new DefaultTableModel();
    tableModel.addColumn("NIK");
    tableModel.addColumn("Nama");
    tableModel.addColumn("Tanggal");
    tableModel.addColumn("Barang");
    tableModel.addColumn("Pinjaman");
    tableModel.addColumn("Persetujuan");
    tableModel.addColumn("Waktu");

 

    try {
        Statement st = conn.getConnection().createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM pinjam");

        while (rs.next()) {
            java.util.Date tanggalDate = rs.getDate("tanggal");
            Object[] rowData = new Object[] {
                rs.getString("nik"),
                rs.getString("nama"),
                rs.getString("tanggal"),
                rs.getString("barang"),
                rs.getString("pinjaman"),
                rs.getString("persetujuan"),
                rs.getString("waktu"),
                
            };

            tableModel.addRow(rowData);
        }

        Tabel.setModel(tableModel);
        st.close(); // Menutup statement, bukan pst.close()
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    }
    hapus();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grup = new javax.swing.ButtonGroup();
        grup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nik = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        Simpan1 = new javax.swing.JButton();
        Hapus1 = new javax.swing.JButton();
        Edit1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Menu = new javax.swing.JComboBox<>();
        Obama = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Tanggal = new com.toedter.calendar.JDateChooser();
        persetujuan = new javax.swing.JComboBox<>();
        waktu = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        Simpan2 = new javax.swing.JButton();
        Edit2 = new javax.swing.JButton();
        Hapus2 = new javax.swing.JButton();
        pencarian = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 840, 240));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("NIK");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel8.setText("NAMA");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 37, -1));

        jLabel11.setText("Tgl Pinjam");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 24));

        nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nikActionPerformed(evt);
            }
        });
        jPanel2.add(nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 210, -1));
        jPanel2.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 210, -1));

        Simpan1.setText("Daftar");
        Simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Simpan1ActionPerformed(evt);
            }
        });
        jPanel2.add(Simpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 569, -1, -1));

        Hapus1.setText("Hapus");
        Hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hapus1ActionPerformed(evt);
            }
        });
        jPanel2.add(Hapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 569, -1, -1));

        Edit1.setText("Edit");
        Edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit1ActionPerformed(evt);
            }
        });
        jPanel2.add(Edit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 569, -1, -1));

        jLabel13.setText("Barang");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 62, -1));

        jLabel14.setText("Pinjaman");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 62, -1));

        Menu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH BARANG --", "BPKB ", "EMAS", "AKTA TANAH", "HANDPHONE", "LAPTOP", "LAPTOP" }));
        jPanel2.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 200, -1));

        Obama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--PILIH PINJAMAN--", "1.000.000", "2.000.000", "3.000.000", "4.000.000", "5.000.000", "6.000.000", "7.000.000", "8.000.000", "9.000.000", "10.000.000" }));
        jPanel2.add(Obama, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 200, -1));

        jLabel15.setText("Waktu");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 62, -1));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projek_Akhir2\\src\\Gambar\\LOGO.png")); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 120, 160));
        jPanel2.add(Tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 210, 30));

        persetujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Persetujuan--", "Terima", "Tolak" }));
        persetujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persetujuanActionPerformed(evt);
            }
        });
        jPanel2.add(persetujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 200, -1));

        waktu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Cicilan--", "3 Bulan", "6 Bulan", "12 Bulan" }));
        jPanel2.add(waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 200, -1));

        jLabel17.setText("Persetujuan");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 62, -1));

        Simpan2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Simpan2.setForeground(new java.awt.Color(204, 0, 204));
        Simpan2.setText("Daftar");
        Simpan2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        Simpan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Simpan2ActionPerformed(evt);
            }
        });
        jPanel2.add(Simpan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 233, 60, 30));

        Edit2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Edit2.setForeground(new java.awt.Color(204, 0, 204));
        Edit2.setText("Edit");
        Edit2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        Edit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit2ActionPerformed(evt);
            }
        });
        jPanel2.add(Edit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 233, 60, 30));

        Hapus2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Hapus2.setForeground(new java.awt.Color(204, 0, 204));
        Hapus2.setText("Hapus");
        Hapus2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        Hapus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hapus2ActionPerformed(evt);
            }
        });
        jPanel2.add(Hapus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 233, 60, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 840, 280));
        jPanel1.add(pencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 180, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 204));
        jButton3.setText("Cari");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 60, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 0, 204));
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 360, 80, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projek_Akhir2\\src\\Gambar\\—Pngtree—blue purple gradient circle_5487754 (1).png")); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, 110, 700, 650));

        jLabel16.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projek_Akhir2\\src\\Gambar\\—Pngtree—blue purple gradient circle_5487754 (1).png")); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, -180, 700, 650));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        int baris = Tabel.rowAtPoint(evt.getPoint());
    String NIK = Tabel.getValueAt(baris, 0).toString();
    nik.setText(NIK);
    String NAMA = Tabel.getValueAt(baris, 1).toString();
    nama.setText(NAMA);

    try {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalString = Tabel.getValueAt(baris, 2).toString();
        Date tanggalDate = dateFormat.parse(tanggalString);

        Tanggal.setDate(tanggalDate);
    } catch (ParseException ex) {
        ex.printStackTrace();
    }
    
    String Barang = Tabel.getValueAt(baris, 3).toString();
    Menu.setSelectedItem(Barang);
    
    String Pinjam = Tabel.getValueAt(baris, 4).toString();
    Obama.setSelectedItem(Pinjam);
    
    String Setuju = Tabel.getValueAt(baris, 5).toString();
    persetujuan.setSelectedItem(Setuju);
    
    String Waktu = Tabel.getValueAt(baris, 6).toString();
    waktu.setSelectedItem(Waktu);
        
    }//GEN-LAST:event_TabelMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cari();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JOptionPane.showMessageDialog(null, "Apakah Yakin Untuk Keluar");
        this.setVisible(false);
        User New = new User();
        New.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Simpan1ActionPerformed

    }//GEN-LAST:event_Simpan1ActionPerformed

    private void Hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hapus1ActionPerformed
        try {

            Koneksi conn = new Koneksi();

            String sql = "DELETE FROM pinjam WHERE nik=?";
            PreparedStatement pst = conn.getConnection().prepareStatement(sql);

            pst.setString(1, nik.getText());

            int rowsAffected = pst.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                table();
            } else {
                JOptionPane.showMessageDialog(null, "NIM tidak ditemukan");
            }

            pst.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan");
        }
    }//GEN-LAST:event_Hapus1ActionPerformed

    private void Edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit1ActionPerformed
     

    }//GEN-LAST:event_Edit1ActionPerformed

    private void nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nikActionPerformed

    private void persetujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persetujuanActionPerformed

    }//GEN-LAST:event_persetujuanActionPerformed

    private void Simpan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Simpan2ActionPerformed
       String tmpl = "yyyy-MM-dd";
        SimpleDateFormat fn = new SimpleDateFormat(tmpl);
        String tanggal = fn.format(Tanggal.getDate());

        try {
            Koneksi conn = new Koneksi();

            String sqlPinjam = "INSERT INTO pinjam (nik, nama, tanggal, barang, pinjaman, persetujuan, waktu) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pstPinjam = conn.getConnection().prepareStatement(sqlPinjam);

            pstPinjam.setString(1, nik.getText());
            pstPinjam.setString(2, nama.getText());
            pstPinjam.setString(3, tanggal);
            pstPinjam.setString(4, Menu.getSelectedItem().toString());
            pstPinjam.setString(5, Obama.getSelectedItem().toString());
            pstPinjam.setString(6, persetujuan.getSelectedItem().toString());
            pstPinjam.setString(7, waktu.getSelectedItem().toString());

            pstPinjam.executeUpdate();
            
          String sqlAngsuran = "INSERT INTO angsuran (nik, nama, pinjaman) VALUES (?, ?, ?)";
        PreparedStatement pstAngsuran = conn.getConnection().prepareStatement(sqlAngsuran);

        pstAngsuran.setString(1, nik.getText());
        pstAngsuran.setString(2, nama.getText());
        pstAngsuran.setString(3, Obama.getSelectedItem().toString());



            pstAngsuran.executeUpdate();
            pstAngsuran.close();

            table();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan");
        }
    }//GEN-LAST:event_Simpan2ActionPerformed

    private void Edit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit2ActionPerformed

    String tmpl = "yyyy-MM-dd";
    SimpleDateFormat fn = new SimpleDateFormat(tmpl);
    String tanggal = fn.format(Tanggal.getDate());

    try {
        Koneksi conn = new Koneksi();

        // Update pinjam table
        String sqlUpdate = "UPDATE pinjam SET nama=?, tanggal=?, barang=?, pinjaman=?, persetujuan=?, waktu=? WHERE nik=?";
        PreparedStatement pstUpdate = conn.getConnection().prepareStatement(sqlUpdate);

        pstUpdate.setString(1, nama.getText());
        pstUpdate.setString(2, tanggal);
        pstUpdate.setString(3, Menu.getSelectedItem().toString());
        pstUpdate.setString(4, Obama.getSelectedItem().toString());
        pstUpdate.setString(5, persetujuan.getSelectedItem().toString());
        pstUpdate.setString(6, waktu.getSelectedItem().toString());
        pstUpdate.setString(7, nik.getText());

        pstUpdate.executeUpdate();
        pstUpdate.close();

        // Insert into angsuran table
    

        // Refresh the table
        table();
        JOptionPane.showMessageDialog(null, "Data berhasil diperbarui");

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan");
    }

    }//GEN-LAST:event_Edit2ActionPerformed

    private void Hapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hapus2ActionPerformed
      try {

            Koneksi conn = new Koneksi();

            String sql = "DELETE FROM pinjam WHERE nik=?";
            PreparedStatement pst = conn.getConnection().prepareStatement(sql);

            pst.setString(1, nik.getText());

            int rowsAffected = pst.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                table();
            } else {
                JOptionPane.showMessageDialog(null, "NIM tidak ditemukan");
            }

            pst.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan");
        }
    }//GEN-LAST:event_Hapus2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pinjam_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pinjam_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pinjam_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pinjam_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pinjam_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit1;
    private javax.swing.JButton Edit2;
    private javax.swing.JButton Hapus1;
    private javax.swing.JButton Hapus2;
    private javax.swing.JComboBox<String> Menu;
    private javax.swing.JComboBox<String> Obama;
    private javax.swing.JButton Simpan1;
    private javax.swing.JButton Simpan2;
    private javax.swing.JTable Tabel;
    private com.toedter.calendar.JDateChooser Tanggal;
    private javax.swing.ButtonGroup grup;
    private javax.swing.ButtonGroup grup2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField pencarian;
    private javax.swing.JComboBox<String> persetujuan;
    private javax.swing.JComboBox<String> waktu;
    // End of variables declaration//GEN-END:variables
}
