/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul3;

import javax.swing.JOptionPane;

/**
 *
 * @author Shafira SS
 */
public class nomer1 extends javax.swing.JFrame {

    /**
     * Creates new form nomer1
     */
    public nomer1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        a = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        b = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        c = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        d = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        informasi = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        e = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        f = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        g = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        h = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        i = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PERPUSTAKAAN DIGITAL");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(2, 5));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        a.setText("Tentang Buku Ini");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        jPanel3.add(a);
        a.setBounds(30, 240, 130, 23);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/7.jpg"))); // NOI18N
        jPanel3.add(jLabel18);
        jLabel18.setBounds(30, 20, 130, 200);

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/8.jpg"))); // NOI18N
        jPanel4.add(jLabel8);
        jLabel8.setBounds(40, 20, 140, 200);

        b.setText("Tentang Buku Ini");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        jPanel4.add(b);
        b.setBounds(35, 240, 130, 23);

        jPanel2.add(jPanel4);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(null);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/11.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel7.add(jLabel15);
        jLabel15.setBounds(30, 20, 140, 200);

        c.setText("Tentang Buku Ini");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        jPanel7.add(c);
        c.setBounds(25, 240, 140, 23);

        jPanel2.add(jPanel7);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(null);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/6.jpg"))); // NOI18N
        jLabel17.setText("jLabel17");
        jPanel9.add(jLabel17);
        jLabel17.setBounds(40, 20, 130, 200);

        d.setText("Tentang Buku Ini");
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        jPanel9.add(d);
        d.setBounds(40, 240, 130, 23);

        jPanel2.add(jPanel9);

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        informasi.setColumns(20);
        informasi.setLineWrap(true);
        informasi.setRows(5);
        informasi.setWrapStyleWord(true);
        jScrollPane1.setViewportView(informasi);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel11);

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(null);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/1.jpg"))); // NOI18N
        jPanel10.add(jLabel14);
        jLabel14.setBounds(30, 20, 127, 200);

        e.setText("Tentang Buku Ini");
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });
        jPanel10.add(e);
        e.setBounds(30, 230, 130, 23);

        jPanel2.add(jPanel10);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(null);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/9.jpg"))); // NOI18N
        jPanel8.add(jLabel19);
        jLabel19.setBounds(30, 20, 130, 200);

        f.setText("Tentang Buku Ini");
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });
        jPanel8.add(f);
        f.setBounds(30, 230, 130, 23);

        jPanel2.add(jPanel8);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(null);

        g.setText("Tentang Buku Ini");
        g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gActionPerformed(evt);
            }
        });
        jPanel6.add(g);
        g.setBounds(30, 230, 130, 23);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/3.jpg"))); // NOI18N
        jPanel6.add(jLabel21);
        jLabel21.setBounds(30, 20, 130, 200);

        jPanel2.add(jPanel6);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(null);

        h.setText("Tentang Buku Ini");
        h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hActionPerformed(evt);
            }
        });
        jPanel5.add(h);
        h.setBounds(50, 230, 120, 23);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul3/5.jpg"))); // NOI18N
        jPanel5.add(jLabel16);
        jLabel16.setBounds(40, 20, 130, 200);

        jPanel2.add(jPanel5);

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel12.setLayout(null);

        i.setText("Reset");
        i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iActionPerformed(evt);
            }
        });
        jPanel12.add(i);
        i.setBounds(40, 200, 120, 23);

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton1);
        jButton1.setBounds(40, 240, 120, 23);

        jPanel2.add(jPanel12);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
    informasi.setText("\bNovel ALTHARIO karya Siti Habibah\b Novel ini mengisahkan tentang Althario Marganamahendra lelaki misterius dan dingin dengan tampang penampilan fisik bak dewa dalam mitologi Yunani. Althario merupakan ketua geng motor di SMA SMA Exsa Dirgantara yang bernama Egryon. Meskipun geng motor dikenal notabene anak-anak nakal, tetapi IQ Althario ini di atas rata-rata, alias ia sangat pandai. Kepandaian Althario ini lah yang membuat teman di sekitarnya kagum kepada dirinya, juga kepada geng motor Egryon. Berkat Althario yang memimpin geng motor ini, nama Egryon semakin dikenal banyak orang. Egryon juga kerap kali mendapatkan julukan sebagai Angel or Devil. Sebab, geng motor ini bisa menjadi malaikat pelindung, tetapi juga bisa menjadi iblis yang mengintimidasi lawannya dalam pertempuran. Dengan sikap dan kewibawaan Althario, tentunya banyak perempuan yang tertarik dengan dirinya, bahkan ingin menjadi kekasihnya. Namun, tidak ada satu orang pun yang berhasil merebut perhatiannya, kecuali seorang cewek bernama Keyzia Marsella Ghisani.Jika anda membayangkan sosok wanita yang anggun, kalem, dan pandai yang mampu merebut hati Althario sang pangeran sekolah, bayangan anda itu salah. Keyzia adalah mantan pembuat masalah di SMA Exsa yang dikenal memiliki kepribadian bawel, bucin, bobrok, dan bodoh, atau yang sering disebut sebagai 4B. Namun, tak dapat dipungkiri bahwa Keyzia memang penampilan fisiknya cantik dan menarik.");
    }//GEN-LAST:event_cActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
    informasi.setText("\bNovel 00.00 karya Ameylia Falensia\b 00.00 bercerita tentang seorang perempuan bernama Lengkara Putri Langit atau kerap disapa Kara. Kehidupan Kara berubah menjadi kacau setelah Erik,"+"ayahnya menikah lagi dengan seorang janda anak satu. Kebahagiaan Kara"+"perlahan terhapuskan satu per satu. Rumah yang tadinya menjadi tempat"+"pulang paling nyaman kini sudah tak dirasakan lagi. Kehadiran saudara tiri membuat kebahagiaan Kara menjadi sebuah kesengsaraan.");        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
    informasi.setText("\bNovel 00.01 karya Ameylia Falensia\b Lengkara harus membuat happy ending-nya sendiri dengan atau tanpa kehadiran Masnaka. Namun, semua proses itu tidaklah mudah. Karena pemeran utama di hidupnya telah mati tanpa meninggalkan pengganti.Ingatan abu-abu tentangmu masih dapat dengan jelas kuingat. Semua akan kutuangkan ke dalam tulisan ini.Tugas Lengkara hanya kembali memutar kisah masa lalunya bersama Masnaka dalam ingatan. Perkara Nilam dan keegoisan Lengkara sudah membuat Masnaka ikut terluka. Sayangnya, waktu lebih senang dengan sebuah perpisahan.Sekala perlahan membuat rangkaian ending yang menyenangkan buat Lengkara. Apakah ini jawaban yang Masnaka kirimkan kepadanya? Bisakah Lengkara menulis kisah bahagianya tanpa seorang Masnaka yang menjadi pemeran utamanya?");    // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
    informasi.setText("\bNovel RETAK karya Azhara Natasya\b Kata orang, tidak ada yang lebih indah dari hidup bersama keluarga yang utuh. Namun bagi Gladys, keluarganya merupakan alasan luka di hatinya. Setelah dikucilkan oleh keluarga karena dianggap sebagai penyebab kematian kakaknya, Gladys pun harus kembali merasakan sakit akibat bullying yang dilakukan teman-teman di sekolahnya. Namun, ada seseorang yang menjadi penyemangat dalam hidupnya. Aldo—kakak kelasnya yang merupakan seorang ketua ekstrakurikuler basket dan cukup populer di sekolahnya. Sayangnya, perbedaan keyakinan menjadi tembok penghalang keduanya dan memunculkan keraguan di hati Gladys. Haruskah ia melepaskan setelah cintanya begitu dalam untuk Aldo? Sementara di sisi lain, ada seseorang yang selalu menunggu Gladys untuk membuka pintu hatinya.");
// TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
    informasi.setText("\bNovel PERGI karya Tere Liye\b menceritakan kisah tentang Bujang yang mencari tujuan hidup, ke mana hendak pergi, melalui kenangan demi kenangan masa lalu, pertarungan hidup-mati, untuk memutuskan kemana langkah kaki akan dibawa. Novel ini merupakan kelanjutan dari sekuel novel Pulang sebelumnya.");    // TODO add your handling code here:
    }//GEN-LAST:event_eActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
    informasi.setText("\bNovel DIA ANGKASA karya Nur Wyna\b Novel Dia Angkasa mengisahkan tentang seorang lelaki bernama Angkasa Naufal Merapi, sosok remaja lelaki yang identik dengan dasi yang diikat di kepalanya, siswa berandalan nomor satu yang disegani di SMA Andromeda, dan dikenal sebagai ketua pada perkumpulan besarnya yang bernama SATROVA. Dalam kehidupannya, kisah indah dan kisah menyenangkan tidak termasuk dalam rangkaiannya.Sampai pada akhirnya, perjalanan hidup mempertemukan Angkasa dengan wanita berbandana biru. Wanita yang mempunyai pengecualian dalam diri Angkasa, wanita yang akhirnya berhasil meredakan ego dan sifat keras kepala Angksa, wanita yang dijaga Angkasa dengan baik, atas  sosok wanita itu adalah Aurelani Aurora.");
     // TODO add your handling code here:
    }//GEN-LAST:event_fActionPerformed

    private void gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gActionPerformed
    informasi.setText("\bNovel DIKTA&HUKUM karya Dhia'an Farah\b Novel Dikta dan Hukum bercerita tentang tokoh bernama Dikta yang merupakan seorang mahasiswa hukum tingkat akhir di salah satu universitas terkenal dan ternama dan ia termasuk mahasiswa yang pintar. Dikta ini digambarkan sebagai tokoh yang sempurna dan idaman para wanita, yakni pintar, kaya, baik, rajin, penyayang, dan berparas ganteng pula. Sedangkan Nadhira adalah seorang anak SMA kelas 12 yang memiliki karakter mager dan pemalas. Berbanding terbalik dengan Dikta yang memiliki sifat disiplin dan serius, sedangkan Nadhira suka mengeluh dan terkenal banyak mau dan sedikit keras kepala. Sosok sempurna seorang Dikta ini ternyata sudah dijodohkan dengan seorang gadis SMA itu, Nadhira yang mungkin banyak yang menganggap sangat berbanding terbalik dengan sosok seorang Dikta.");// TODO add your handling code here:
    }//GEN-LAST:event_gActionPerformed

    private void hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hActionPerformed
   informasi.setText("\bNovel TELUK ALASKA karya Dhia'an Farah\b Menceritakan tentang persahabaan sepasang anak remaja yang sudah terjalin hingga 7 tahun, mereka bernama Alister Raygan dan Anatasya Mysha. Hingga pada suatu hari, Alister harus ikut pindah mengikuti kedua orang tuanya yang dipindah tugaskan ke Jakarta.");
// TODO add your handling code here:
    }//GEN-LAST:event_hActionPerformed

    private void iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iActionPerformed
    informasi.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_iActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Object[] pilihan = {"IYA", "CANCEL"};
        int cthOption = JOptionPane.showOptionDialog(this, "APAKAH ANDA INGIN KELUAR?", "option dialog", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, pilihan, pilihan[1]);
        if(cthOption == 0){
            JOptionPane.showMessageDialog(this, "TEKAN OKE UNTUK KELUAR!");
            System.exit(0);
        } else if(cthOption == 1){
            JOptionPane.showMessageDialog(this, "ANDA AKAN KEMBALI KE PROGRAM");
            informasi.setText("");
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nomer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nomer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nomer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nomer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nomer1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a;
    private javax.swing.JButton b;
    private javax.swing.JButton c;
    private javax.swing.JButton d;
    private javax.swing.JButton e;
    private javax.swing.JButton f;
    private javax.swing.JButton g;
    private javax.swing.JButton h;
    private javax.swing.JButton i;
    private javax.swing.JTextArea informasi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
