/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projek_akhir;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Angsuran extends javax.swing.JFrame {

    /**
     * Creates new form Angsuran
     */
    public Angsuran() {
        initComponents();
        table();
    }
    
    private void table() {
    Koneksi conn = new Koneksi();
    DefaultTableModel tableModel = new DefaultTableModel();
    tableModel.addColumn("NO");
    tableModel.addColumn("NIK");
    tableModel.addColumn("Nama");
    tableModel.addColumn("Sisa Angsuran");


 

    try {
        Statement st = conn.getConnection().createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM angsuran");

        while (rs.next()) {
      
            Object[] rowData = new Object[] {
                rs.getString("no"),
                rs.getString("nik"),
                rs.getString("nama"),
                rs.getString("pinjaman"),
               
            };

            tableModel.addRow(rowData);
        }

        Tabel.setModel(tableModel);
        st.close(); // Menutup statement, bukan pst.close()
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        angsur = new javax.swing.JTextField();
        pinjaman = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nik = new javax.swing.JTextField();
        Hitung = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        angsuran = new javax.swing.JTextField();
        Simpan3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ANGSURAN");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 290, 60));

        jLabel2.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PENGGUNA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 290, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIK");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ANGSURAN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PINJAMAN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        nama.setBackground(new java.awt.Color(204, 0, 204));
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 278, 230, 30));

        angsur.setBackground(new java.awt.Color(204, 0, 204));
        angsur.setForeground(new java.awt.Color(255, 255, 255));
        angsur.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(angsur, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 418, 230, 30));

        pinjaman.setBackground(new java.awt.Color(204, 0, 204));
        pinjaman.setForeground(new java.awt.Color(255, 255, 255));
        pinjaman.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(pinjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 498, 230, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NAMA");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projek_Akhir2\\src\\Gambar\\LOGO.png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 120, 160));

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projek_Akhir2\\src\\Gambar\\—Pngtree—blue purple gradient circle_5487754 (1).png")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -350, 700, 660));

        nik.setBackground(new java.awt.Color(204, 0, 204));
        nik.setForeground(new java.awt.Color(255, 255, 255));
        nik.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 348, 230, 30));

        Hitung.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Hitung.setForeground(new java.awt.Color(204, 0, 204));
        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        jPanel1.add(Hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, -1, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 204));
        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, -1, 30));

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 440, 280));

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("ANGSURAN");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, -1, -1));

        angsuran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(angsuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 230, 30));

        Simpan3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Simpan3.setForeground(new java.awt.Color(204, 0, 204));
        Simpan3.setText("Bayar");
        Simpan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Simpan3ActionPerformed(evt);
            }
        });
        jPanel1.add(Simpan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 550, -1, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 204));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 630, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
//       int Pinjaman = Integer.parseInt(pinjaman.getText());
//       int Angsuran = Integer.parseInt(angsur.getText());
//       
//       int total = Pinjaman - Angsuran;
//       String totalString = String.valueOf(total);
//       angsuran.setText(totalString);
                              
//    try {
//        int Pinjaman = Integer.parseInt(pinjaman.getText());
//        int Angsuran = Integer.parseInt(angsur.getText());
//
//        int total = Pinjaman - Angsuran;
//        String totalString = String.format("%,d", total);
//        angsuran.setText(totalString);
//
//    } catch (NumberFormatException e) {
//        JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid numeric value.");
//    }
                                         
     try {
        NumberFormat format = NumberFormat.getNumberInstance();

        String pinjamanText = pinjaman.getText();
        String angsuranText = angsur.getText();

        Number pinjamanNumber = format.parse(pinjamanText);
        Number angsuranNumber = format.parse(angsuranText);

        double Pinjaman = pinjamanNumber.doubleValue();
        double Angsuran = angsuranNumber.doubleValue();

        double total = Pinjaman - Angsuran;
        String totalString = format.format(total);
        angsuran.setText("Rp."+totalString);

    } catch (ParseException e) {
        JOptionPane.showMessageDialog(null, "Invalid input. Please enter valid numeric values.");
    }
    }//GEN-LAST:event_HitungActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       nik.setText("");
       nama.setText("");
       angsur.setText("");
       pinjaman.setText("");
       angsuran.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        int baris = Tabel.rowAtPoint(evt.getPoint());

        String NO = Tabel.getValueAt(baris, 1).toString();
        nik.setText(NO);

        String NAMA = Tabel.getValueAt(baris,2).toString();
        nama.setText(NAMA);

        String PINJAMAN = Tabel.getValueAt(baris, 3).toString();
        pinjaman.setText(PINJAMAN);
    }//GEN-LAST:event_TabelMouseClicked

    private void Simpan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Simpan3ActionPerformed
        
        try {
            Koneksi conn = new Koneksi();

            String sqlUpdate = "UPDATE angsuran SET nama=?, pinjaman=? WHERE nik=?";
            PreparedStatement pstUpdate = conn.getConnection().prepareStatement(sqlUpdate);

            pstUpdate.setString(1, nama.getText());
            pstUpdate.setString(2, angsuran.getText());
            pstUpdate.setString(3, nik.getText());
      

            pstUpdate.executeUpdate();
            pstUpdate.close();

            table();
            JOptionPane.showMessageDialog(null, "Data berhasil diperbarui");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan");
        }
    }//GEN-LAST:event_Simpan3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            JOptionPane.showMessageDialog(null, "Yakin Ingin Keluar","",JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            Admin admin = new Admin();
            admin.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Angsuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Angsuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Angsuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Angsuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Angsuran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hitung;
    private javax.swing.JButton Simpan3;
    private javax.swing.JTable Tabel;
    private javax.swing.JTextField angsur;
    private javax.swing.JTextField angsuran;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField pinjaman;
    // End of variables declaration//GEN-END:variables
}
