/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugascrud;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Shafira SS
 */
public class perpus extends javax.swing.JFrame {

    /**
     * Creates new form perpus
     */
    public perpus() {
        conn = new Koneksidb();
        initComponents();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pinjam = new javax.swing.JTextField();
        nim = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        buku = new javax.swing.JTextField();
        balik = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        tampil = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jTextField5.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setText("NO INDUK");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 60, 70, 16);

        jLabel2.setText("NAMA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 100, 36, 16);

        jLabel3.setText("BUKU");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 140, 30, 16);

        jLabel4.setText("TANGGAL PEMINJAMAN");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 170, 150, 16);

        jLabel5.setText("TANGGAL PENGEMBALIAN");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 210, 150, 16);
        jPanel1.add(pinjam);
        pinjam.setBounds(220, 170, 430, 30);
        jPanel1.add(nim);
        nim.setBounds(220, 50, 430, 30);
        jPanel1.add(nama);
        nama.setBounds(220, 90, 430, 30);
        jPanel1.add(buku);
        buku.setBounds(220, 130, 430, 30);
        jPanel1.add(balik);
        balik.setBounds(220, 210, 430, 30);

        simpan.setBackground(new java.awt.Color(153, 153, 255));
        simpan.setText("SIMPAN");
        simpan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel1.add(simpan);
        simpan.setBounds(540, 250, 60, 22);

        edit.setBackground(new java.awt.Color(153, 153, 255));
        edit.setText("EDIT");
        edit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit);
        edit.setBounds(470, 250, 60, 22);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setText("                     FORM PEMINJAMAN BUKU PERPUSTAKAAN");
        jLabel6.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 690, 25);

        jTabbedPane1.addTab("FORM PEMINJAMAN", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(null);

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldata);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 679, 227);

        tampil.setBackground(new java.awt.Color(153, 153, 255));
        tampil.setText("TAMPIL");
        tampil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilActionPerformed(evt);
            }
        });
        jPanel2.add(tampil);
        tampil.setBounds(240, 270, 47, 22);

        hapus.setBackground(new java.awt.Color(153, 153, 255));
        hapus.setText("HAPUS");
        hapus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel2.add(hapus);
        hapus.setBounds(370, 270, 44, 22);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setText("                     DATA PEMINJAMAN BUKU PERPUSTAKAAN");
        jLabel7.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 0, 690, 25);

        jTabbedPane1.addTab("DATA PEMINJAMAN", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilActionPerformed
    tampilData();
        // TODO add your handling code here:
    }//GEN-LAST:event_tampilActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
    int selectedRow = tabeldata.getSelectedRow();

    if (selectedRow >= 0) {
        String kode = tabeldata.getValueAt(selectedRow, 2).toString();
        try {
            Statement st = conn.getConnection().createStatement();
            st.executeUpdate("DELETE FROM peminjaman WHERE no_induk = '" + kode + "'");
            st.close();
            DefaultTableModel model = (DefaultTableModel) tabeldata.getModel();
            model.removeRow(selectedRow);
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris yang akan dihapus terlebih dahulu.");
    }   // TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        try {
            Statement st = conn.getConnection().createStatement();
            st.executeUpdate("INSERT INTO peminjaman VALUES('"+  nim.getText()+ "',"+ " '"
                + nama.getText()+"',"+ " '"+ buku.getText()
                +"',"+ " '"+ pinjam.getText()+"',"+ " '"+ balik.getText() +"')");
            st.close();
            JOptionPane.showMessageDialog(this, "data berhasil disimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "data gagal disimpan");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_simpanActionPerformed

    private void tabeldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldataMouseClicked
        int row = tabeldata.getSelectedRow();
        nim.setText((String) tabeldata.getValueAt(row, 0));
        nama.setText((String) tabeldata.getValueAt(row, 1));
        buku.setText((String) tabeldata.getValueAt(row, 2));
        pinjam.setText((String) tabeldata.getValueAt(row, 3));
        balik.setText((String) tabeldata.getValueAt(row, 4));
        // TODO add your handling code here:
    }//GEN-LAST:event_tabeldataMouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
    try {
        Statement statement = conn.getConnection().createStatement();
        int updatedRows = statement.executeUpdate("UPDATE peminjaman SET nama='" + nama.getText()
                + "', nama_buku='" + buku.getText() + "', tgl_pinjam='" + pinjam.getText()
                + "', tgl_pengembalian='" + balik.getText() + "' WHERE no_induk='" + nim.getText() + "'");
        statement.close();

        if (updatedRows > 0) {
            JOptionPane.showMessageDialog(this, "Data berhasil diubah");
            bersihkan();
            tampilData();
        } else {
            JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
        }
    } catch (Exception t) {
        System.out.println(t.getMessage());
    }         // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed
    private void bersihkan(){
            nim.setText("");
            nama.setText("");
            buku.setText("");
            pinjam.setText("");
            balik.setText("");
        }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perpus().setVisible(true);
            }
        });
    }
public void tampilData(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("NO_INDUK");
        tbl.addColumn("NAMA");
        tbl.addColumn("NAMA_BUKU");
        tbl.addColumn("TGL_PINJAM");
        tbl.addColumn("TGL_PENGEMBALIAN");
               
        tabeldata.setModel(tbl); // tbl_mahasiswa sesuaikan dengan variable pada table
        try {
            Statement st = conn.getConnection().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM peminjaman");
            while (rs.next()) {
                tbl.addRow( new Object[] {
                    rs.getString("no_induk"),
                    rs.getString("nama"),
                    rs.getString("nama_buku"),
                    rs.getString("tgl_pinjam"),   
                    rs.getString("tgl_pengembalian")
                });
                tabeldata.setModel(tbl);
            }
        } catch (Exception e) {
        }
    }

    Koneksidb conn;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balik;
    private javax.swing.JTextField buku;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nim;
    private javax.swing.JTextField pinjam;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabeldata;
    private javax.swing.JButton tampil;
    // End of variables declaration//GEN-END:variables
}
